const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
};

const ERROR_CODES = {
  // Authentication errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INVALID_TOKEN: 'INVALID_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
  INVALID_TOKEN_FORMAT: 'INVALID_TOKEN_FORMAT',
  
  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',
  
  // Post errors
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_REVIEWED: 'POST_ALREADY_REVIEWED',
  POST_NOT_MODIFIABLE: 'POST_NOT_MODIFIABLE',
  
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  
  // Permission errors
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // Rate limiting
  RATE_LIMIT: 'RATE_LIMIT',
  
  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR'
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  EDITOR: 'EDITOR',
  PENDING: 'PENDING'
};

const POST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
};

const VALIDATION = {
  EMAIL_MAX: 100,
  NAME_MAX: 100,
  PASSWORD_MIN: 6,
  TITLE_MIN: 1,
  TITLE_MAX: 200,
  CONTENT_MIN: 10,
  CONTENT_MAX: 5000,
  REJECTION_REASON_MIN: 10,
  REJECTION_REASON_MAX: 500
};

const TOKEN_TYPES = {
  ACCESS: 'access',
  REFRESH: 'refresh'
};

const TOKEN_EXPIRATION = {
  ACCESS_TOKEN: process.env.JWT_ACCESS_EXPIRY || '5m',
  REFRESH_TOKEN: process.env.JWT_REFRESH_EXPIRY || '7d'
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
  USER_ROLES,
  POST_STATUS,
  PAGINATION,
  VALIDATION,
  TOKEN_TYPES,
  TOKEN_EXPIRATION
};