const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};

const ERROR_CODES = {
  // Authentication errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_REQUIRED: 'ACCESS_TOKEN_REQUIRED', // updated
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN', // added

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  PASSWORD_RESET_REQUIRED: 'PASSWORD_RESET_REQUIRED',
  PASSWORD_ALREADY_SET: 'PASSWORD_ALREADY_SET',

  // Post errors
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_REVIEWED: 'POST_ALREADY_REVIEWED',
  POST_NOT_MODIFIABLE: 'POST_NOT_MODIFIABLE',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Permission errors
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR'
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

const POST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
};

const VALIDATION = {
  EMAIL_MAX: 100,
  NAME_MAX: 100,
  PASSWORD_MIN: 6,
  TITLE_MAX: 200,
  CONTENT_MAX: 5000,
  REJECTION_REASON_MAX: 500
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
  USER_ROLES,
  POST_STATUS,
  PAGINATION,
  VALIDATION
};
